/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#263143",
        "surface-container-high": "#222a3d",
        "on-secondary": "#003824",
        "background": "#0b1326",
        "on-background": "#dae2fd",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-tint": "#7bd0ff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#001e2c",
        "tertiary-fixed-dim": "#bcc7de",
        "surface-variant": "#2d3449",
        "inverse-surface": "#dae2fd",
        "primary-fixed": "#c4e7ff",
        "on-secondary-fixed": "#002113",
        "inverse-primary": "#00668a",
        "secondary-container": "#00a572",
        "on-primary-fixed-variant": "#004c69",
        "on-surface-variant": "#bdc8d1",
        "primary": "#8ed5ff",
        "surface-container-lowest": "#060e20",
        "outline-variant": "#3e484f",
        "tertiary": "#c2cde5",
        "surface-container-low": "#131b2e",
        "primary-fixed-dim": "#7bd0ff",
        "surface-dim": "#0b1326",
        "tertiary-container": "#a7b2c9",
        "primary-container": "#38bdf8",
        "surface": "#0b1326",
        "inverse-on-surface": "#283044",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-highest": "#2d3449",
        "error": "#ffb4ab",
        "tertiary-fixed": "#d8e3fb",
        "on-primary": "#00354a",
        "on-tertiary-fixed": "#111c2d",
        "on-primary-container": "#004965",
        "on-secondary-container": "#00311f",
        "on-tertiary-container": "#394458",
        "outline": "#87929a",
        "secondary-fixed": "#6ffbbe",
        "surface-bright": "#31394d",
        "secondary": "#D5DEEF"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
